name: Collect System Info

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Collect System Info
    runs-on:
      - codebuild-github-marchof-runs-on-codebuild-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - run: sudo apt-get install -y lshw
    - run: sudo lshw